---
# tasks file for aria2
- name: mkdir path
  file:
    path: /etc/aria2
    state: directory
    mode: '0755'

- name: aria2.conf 
  template:
    src: aria2.conf.j2 
    dest: /etc/aria2/aria2.conf

- name: aria2.session 
  template:
    src: aria2.session 
    dest: /etc/aria2/aria2.session

- name: install aria2
  yum: 
    name: 
      - aria2
      - nginx
    state: latest

- name: add aria2 to systemd service
  template:
    src: aria2.service
    dest: /usr/lib/systemd/system/aria2.service

- name: nginx configure file
  template:
    src: ariaNg.conf
    dest: /etc/nginx/conf.d/

- name: ariaNg web
  copy: 
    src: ariaNg
    dest: /srv
    owner: nginx
    group: nginx
  changed_when: 2 > 1
  notify:
    - restart nginx
    - restart aria2
  tags: ariaNg 

